# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/cli.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fproto/cli.proto\x12\x03\x63li\"C\n\x06Option\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x14\n\x0clong_options\x18\x02 \x03(\t\x12\x15\n\rshort_options\x18\x03 \x03(\t\"\n\n\x08\x41rgument\"\x99\x01\n\x07\x43ommand\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1c\n\x07options\x18\x02 \x03(\x0b\x32\x0b.cli.Option\x12 \n\targuments\x18\x03 \x03(\x0b\x32\r.cli.Argument\x12\"\n\x0csub_commands\x18\x04 \x03(\x0b\x32\x0c.cli.Command\x12\x12\n\x05usage\x18\x05 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_usage\"g\n\x04Line\x12\x0e\n\x06\x62uffer\x18\x01 \x01(\t\x12 \n\x04type\x18\x02 \x01(\x0e\x32\x12.cli.Line.LineType\"-\n\x08LineType\x12\t\n\x05STDIN\x10\x00\x12\n\n\x06STDOUT\x10\x01\x12\n\n\x06STDERR\x10\x02\x32)\n\x03\x63li\x12\"\n\x04\x63\x61ll\x12\t.cli.Line\x1a\t.cli.Line\"\x00(\x01\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.cli_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OPTION._serialized_start=24
  _OPTION._serialized_end=91
  _ARGUMENT._serialized_start=93
  _ARGUMENT._serialized_end=103
  _COMMAND._serialized_start=106
  _COMMAND._serialized_end=259
  _LINE._serialized_start=261
  _LINE._serialized_end=364
  _LINE_LINETYPE._serialized_start=319
  _LINE_LINETYPE._serialized_end=364
  _CLI._serialized_start=366
  _CLI._serialized_end=407
# @@protoc_insertion_point(module_scope)
