# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import cli_pb2 as proto_dot_cli__pb2


class cliStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.call = channel.stream_stream(
                '/cli.cli/call',
                request_serializer=proto_dot_cli__pb2.Line.SerializeToString,
                response_deserializer=proto_dot_cli__pb2.Line.FromString,
                )


class cliServicer(object):
    """Missing associated documentation comment in .proto file."""

    def call(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_cliServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'call': grpc.stream_stream_rpc_method_handler(
                    servicer.call,
                    request_deserializer=proto_dot_cli__pb2.Line.FromString,
                    response_serializer=proto_dot_cli__pb2.Line.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cli.cli', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class cli(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def call(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/cli.cli/call',
            proto_dot_cli__pb2.Line.SerializeToString,
            proto_dot_cli__pb2.Line.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
