# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/cli.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fproto/cli.proto\x12\x03\x63li\"\x16\n\x04Line\x12\x0e\n\x06\x62uffer\x18\x01 \x01(\t2)\n\x03\x63li\x12\"\n\x04\x63\x61ll\x12\t.cli.Line\x1a\t.cli.Line\"\x00(\x01\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.cli_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LINE._serialized_start=24
  _LINE._serialized_end=46
  _CLI._serialized_start=48
  _CLI._serialized_end=89
# @@protoc_insertion_point(module_scope)
